In [1]:
import numpy as np
import pandas as pd
import os

In [6]:
os.chdir(r'C:\Users\Helio\Documents\ALL THAT MATTERS\IC\csv')

In [18]:
data = pd.read_csv(r'TitlesLabelednoComma.csv', encoding="utf-8", sep=';')

In [19]:
data

Title  \
0                A economia chilena: forte mas desigual    
1                                    Uma líder discreta    
2      China lança as maiores reformas econômicas e s...   
3      Juízes argentinos pedem medidas do governo par...   
4      Obama cede à pressão e anuncia mudanças na ref...   
5      Adeus a 2013 sem a reforma da imigração nos Es...   
6                            O fim da esperança em Gaza    
7      Oito países realizam o maior exercício militar...   
8                “É por Mandela que agora somos livres”    
9      “Só consideram provocação quando desenhamos Ma...   
10     Revista já havia sido atacada em 2011 por capa...   
11     Dallas lava suas feridas e relembra Kennedy 50...   
12                  O crime marca a eleição em Honduras    
13     O primeiro presidente que reconheceu o poder d...   
14     Santos terá que enfrentar o voto em branco e o...   
15     As duas leis decretadas por Maduro aumentam o ...   
16                          A sentença do “bunga bunga”    
17     O PIB mexicano sobe 084% no terceiro trimestre...   
18     Yellen conquista primeiro voto para presidir B...   
19                                     Um murro na mesa    
20     O Senado elimina o veto minoritário a nomeaçõe...   
21     Grupos civis armados avançam na tomada de muni...   
22     De Kennedy a Obama dois símbolos de suas geraç...   
23                                  Quem matou Kennedy?    
24     Rei é operado do quadril pela quinta vez e só ...   
25     Colômbia espera que as FARC renunciem ao uso d...   
26     Uruguai: as vacas que transformaram a economia...   
27                    O soviético toma o leme argentino    
28     Polícia confirma que detido é autor dos dispar...   
29     Espanha prepara uma lei de segurança para puni...   
...                                                  ...   
37326   Janot livra Temer e diz que presidente não po...   
37327   Moro é a personalidade mais popular do Brasil...   
37328   Deltan convoca mais uma vez o povo para ir às...   
37329       João Doria e Jair Bolsonaro dividem palanque   
37330       Moro é atacado mas não perde a linha de JUIZ   
37331   LULA em desespero TOTAL! Pede socorro a amigo...   
37332   Delegado da PF propõe: ‘Reeleição zero! Se po...   
37333   Defesa de Cabral alega que ele tem cleptomani...   
37334   Urgente! Sérgio Moro vai à Câmara e detona re...   
37335    Renan Calheiros quer aliança com Lula para 2018   
37336   Adriana Ancelmo mulher de CABRAL: da origem p...   
37337   Cunha diz que Moro quer mantê-lo PRESO como ‘...   
37338   Acostumada com o STF defesa de Cunha fica sur...   
37339   Deputado petista convoca militância a fechar ...   
37340   Ministra pede ao STF mesmo tratamento dado a ...   
37341   EXCLUSIVO: Mulher de Cunha pode ser presa a q...   
37342   O Brilhante Sérgio Moro recebe medalha da Jus...   
37343   AGONIA: José Dirceu divulga nova carta sobre ...   
37344   Bolsonaro e Sérgio Moro juntos no Aeroporto I...   
37345       Deputado petista ataca Sérgio Moro na Câmara   
37346   Aécio diz que povo tem que engolir perda de d...   
37347         URGENTE: Sérgio Moro condena Eduardo Cunha   
37348   Cármen Lúcia fecha pauta de julgamentos do ST...   
37349   O FALSO: Joaquim Barbosa PETISTA detona Temer...   
37350     Ciro Gomes ameaça a dar um tiro em Sérgio Moro   
37351   Gilmar dá aval para investigar vazamento: ‘Fa...   
37352   Edson Fachin autoriza interrogatória à Renan ...   
37353   EXPLOSIVO: Odebrecht confirma que contas de p...   
37354        Lula perde mais uma para o juiz Sérgio Moro   
37355                                                NaN   

                                                     URL  Label  
0      https://brasil.elpais.com/brasil/2013/11/17/in...    0.0  
1      https://brasil.elpais.com/brasil/2013/11/16/in...    0.0  
2      https://brasil.elpais.com/brasil/2013/11/19/in...    0.0  
3      https://brasil.elpais.com/brasil/2013/11/19/in...    0.0  


In [20]:
#eliminate last row that contains NaN Values
data = data.iloc[0:37355,:]

In [23]:
data = data.dropna(subset = ['Title', 'URL'])

In [25]:
from sklearn import preprocessing

In [27]:
label_encoder = preprocessing.LabelEncoder()
y = label_encoder.fit_transform(data.Label.values)
x = data.Title.values

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(x, y,
                                                random_state = 42,
                                                test_size = 0.2,
                                                stratify = y) 

In [35]:
import collections

In [37]:
collections.Counter(Ytrain)

Counter({0: 25694, 1: 4133})

In [38]:
collections.Counter(Ytest)

Counter({0: 6424, 1: 1033})

In [39]:
Xtrain.shape, Xtest.shape

((29827,), (7457,))

## TF-IDF APPROACH

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk

In [47]:
pt_stopwords = set(nltk.corpus.stopwords.words('portuguese'))

In [48]:
tfidf = TfidfVectorizer(min_df = 3, strip_accents = 'unicode',
                        analyzer = 'word', token_pattern = '\w{1,}',
                        ngram_range = (1,3), sublinear_tf = 1, stop_words = pt_stopwords)

In [49]:
tfidf.fit(Xtrain), tfidf.fit(Xtest)

(TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
         dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
         lowercase=True, max_df=1.0, max_features=None, min_df=3,
         ngram_range=(1, 3), norm='l2', preprocessor=None, smooth_idf=True,
         stop_words={'estivéssemos', 'estiverem', 'fora', 'tuas', 'estávamos', 'esteja', 'fui', 'até', 'as', 'serei', 'um', 'nossos', 'nossas', 'tinham', 'pelas', 'fomos', 'tenho', 'fôramos', 'houvéramos', 'mais', 'teríamos', 'sua', 'estiver', 'estavam', 'ou', 'essas', 'este', 'estão', 'tive', 'lhes', 'tivem...u', 'houvera', 'quando', 'esse', 'tua', 'houvemos', 'elas', 'houverem', 'seremos', 'a', 'estiveram'},
         strip_accents='unicode', sublinear_tf=1, token_pattern='\\w{1,}',
         tokenizer=None, use_idf=True, vocabulary=None),
 TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
         dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
         lowercase=True,

In [50]:
Xtrain_tfidf = tfidf.transform(Xtrain)
Xtest_tfidf = tfidf.transform(Xtest)

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
classif = LogisticRegression()
classif.fit(Xtrain_tfidf, Ytrain)
pred = classif.predict_proba(Xtest_tfidf)

In [53]:
def multiclass_logloss(actual, predicted, eps=1e-15):
    """Multi class version of Logarithmic Loss metric.
    :param actual: Array containing the actual target classes
    :param predicted: Matrix with class predictions, one probability per class
    """
    # Convert 'actual' to a binary array if it's not already:
    if len(actual.shape) == 1:
        actual2 = np.zeros((actual.shape[0], predicted.shape[1]))
        for i, val in enumerate(actual):
            actual2[i, val] = 1
        actual = actual2

    clip = np.clip(predicted, eps, 1 - eps)
    rows = actual.shape[0]
    vsota = np.sum(actual * np.log(clip))
    return -1.0 / rows * vsota

In [54]:
loss1 = multiclass_logloss(Ytest, pred)
print('Log loss: {}'.format(loss1))

Log loss: 0.14828358506107256


In [58]:
y_pred = classif.predict(Xtest_tfidf)

In [60]:
y_pred = classif.predict(Xtest_tfidf)
confmat = confusion_matrix(y_true=Ytest, y_pred=y_pred)
print(confmat)

[[6408   16]
 [ 371  662]]


In [61]:
classif.score(Xtest_tfidf, Ytest)

0.9481024540700014

In [72]:
y_proba = classif.predict_proba(Xtest_tfidf)

In [74]:
y_proba = y_proba[:,0]

In [75]:
y_proba

array([0.96876477, 0.99319261, 0.95287178, ..., 0.9574706 , 0.98373487,
       0.92727258])

In [76]:
y_proba > 0.13

array([ True,  True,  True, ...,  True,  True,  True])

In [77]:
Ytest

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)